# Data configs
batch_size: 16
dataset_name: mnist
image_size: 28

# Model configs
device: cuda
embed_dim: 64
in_channels: 1
n_classes: 10
n_encoder: 2
n_heads: 8
patch_size: 7

# Training configs
epochs: 2
lr: 0.001

# Other configs
model_path: ./experiments/models/mnist_model.pt
results_dir: ./experiments/results/mnist
seed: 42
